<?php //@ARGS _content, context, assetRoot, title ?>
<html>
	<head>
		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name='viewport' content='width=device-width, initial-scale=1.0' />
		<title>{==$title=}</title>
		<meta name="description" content="A story by Herman Melville, processed">
		<link rel="stylesheet" type="text/css" href="assets/css/style.css">
	</head>
	<body>
		{==$_content=}
		<script
		  src="https://code.jquery.com/jquery-3.3.1.min.js"
		  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
		  crossorigin="anonymous"></script>
  		<script src="https://cdn.jsdelivr.net/npm/vue@2.5.21/dist/vue.js"></script>
		<script src="assets/js/main.js"></script>
	</body>
</html>